# 用户创建知识库
POST http://127.0.0.1:9090/knowledge_base/create-knowledge-base
Content-Type: application/json
Accept: application/json

{
  "kb_name": "lyh1",
  "desc": "lyh的第一个知识库",
  "user_id": "d078b124cf27413bbb99f6484782e98c"
}

###
# 获取用户知识库列表
GET http://127.0.0.1:9090/knowledge_base/get-knowledge-base?user_id=d078b124cf27413bbb99f6484782e98c
Content-Type: application/json
Accept: application/json
